excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - force_try
  - redundant_string_enum_value
  - trailing_whitespace
  - line_length
