FASTLANE_HIDE_CHANGELOG = true
FASTLANE_SKIP_UPDATE_CHECK = true
fastlane_require 'dotenv'


default_platform(:ios)


platform :ios do
  before_all do
    ENV["SLACK_URL"] = ENV["SLACK_WEBHOOK_URL"]
    setup_circle_ci
end
 desc "Danger PR Validation"
  lane :DangerPRValidation do
    danger(
      danger_id: "PR_VALIDATION",
      dangerfile: "./DangerfilePRMetaValidation"
     )
 end

 desc "Danger publish test results"
  lane :iosDangerPostCI do
    danger(
      danger_id: "POST_CI",
     )
 end
  desc "FASTLANE - Integration test run"
  lane :unit_tests_integration_tests do
	scan(
	    project: "KarhooSDK.xcodeproj",
	    scheme: "KarhooSDK",
	    device: "iPhone 11",
            deployment_target_version: "14.0",
	    code_coverage: true,
	    clean: true,
	    output_types: "junit",
            output_files: "NetworkSDKTests.xml"
    )
  end
  desc "Xcov Report"
  lane :XcovReport do
    xcov(
      project: "KarhooSDK.xcodeproj",
      scheme: "KarhooSDK",
      output_directory: "fastlane/test_output",
      ignore_file_path: "./*view.swift",
    )
  end
end