name: Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!develop'
      - '!master'
      - '!release*'

jobs:
  Unit_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bundle install
        run: bundle install
      - name: Run Unit Tests
        run:
          xcodebuild -workspace 'KarhooSDK.xcworkspace' -scheme 'KarhooSDK' -destination 'platform=iOS Simulator,name=iPhone 11' test | xcpretty --test --color
#      - name: Fastlane Xcov report
#        run: fastlane ios XcovReport

  Build_Project:
    runs-on: macos-latest
    needs: [Unit_tests]
    steps:
      - uses: actions/checkout@v2
      - name: Build SDK
        run:
          xcodebuild -workspace 'KarhooSDK.xcworkspace' -scheme 'KarhooSDK' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO | xcpretty
